name: app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  intl: ^0.19.0
  footer: ^0.0.4
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets: 
    - image/
    - assets/jitter-animaton/images/frown.png
    - assets/jitter-animaton/images/wifi.png
    - assets/jitter-animaton/images/database.png
    - assets/jitter-animaton/images/battery.png
    - assets/jitter-animaton/images/cellular-signal.png
    - assets/jitter-animaton/images/cellular-signal-5RF.png
    - assets/jitter-animaton/images/bell.png
    - assets/jitter-animaton/images/arrow-right.png
    - assets/jitter-animaton/images/smile.png
    - assets/jitter-animaton/images/battery-xTP.png
    - assets/jitter-animaton/images/cellular-signal-tqj.png
    - assets/jitter-animaton/images/add.png
    - assets/jitter-animaton/images/location-arrow.png
    - assets/jitter-animaton/images/wifi-Sjo.png
    - assets/jitter-animaton/images/battery-7Lh.png
    - assets/jitter-animaton/images/wifi-ZEm.png
    - assets/jitter-animaton/images/bell-NXP.png
    - assets/jitter-animaton/images/nav.png
    - assets/jitter-animaton/images/location-arrow-GGV.png
    - assets/jitter-animaton/images/battery-P5f.png
    - assets/jitter-animaton/images/icon-2.png
    - assets/jitter-animaton/images/info.png
    - assets/jitter-animaton/images/location-arrow-gw7.png
    - assets/jitter-animaton/images/dot-1.png
    - assets/jitter-animaton/images/battery-BbK.png
    - assets/jitter-animaton/images/cellular-signal-jpq.png
    - assets/jitter-animaton/images/bell-Yiq.png
    - assets/jitter-animaton/images/nav-YPF.png
    - assets/jitter-animaton/images/vector.png
    - assets/jitter-animaton/images/clock.png
    - assets/application/images/wifi-ixM.png
    - assets/application/images/bell-zdb.png
    - assets/jitter-animaton/images/nav-sPs.png
    - assets/jitter-animaton/images/wifi-brD.png
    - assets/application/images/vector-qVP.png
    - assets/jitter-animaton/images/frame-1.png
    - assets/jitter-animaton/images/location-arrow-Hr5.png
    - assets/application/images/add-wG9.png
    - assets/application/images/loading-animation.png
    - assets/jitter-animaton/images/moon.png
    - assets/application/images/slash.png
    - assets/application/images/smile-G37.png
    - assets/jitter-animaton/images/cellular-signal-LM3.png
    - assets/jitter-animaton/images/bell-SEy.png
    - assets/application/images/frame-1-1zD.png
    - assets/application/images/info-Au3.png
    - assets/application/images/loading-animation-y9f.png
    - assets/application/images/moon-AKw.png
    - assets/application/images/icon.png
    - assets/application/images/ic-round-light-mode.png
    - assets/application/images/dot-1-TYh.png
    - assets/jitter-animaton/images/dot-1-i3F.png
    - assets/application/images/location-arrow-uuX.png
    - assets/application/images/clock-FmX.png
    - assets/application/images/frown-m2u.png
    - assets/application/images/fluent-shape-union-16-filled.png
    - assets/application/images/component-button.png
    - assets/jitter-animaton/images/folder.png
    - assets/application/images/battery-6wX.png
    - assets/jitter-animaton/images/button2.png
    - assets/application/images/button2-ems.png
    - assets/jitter-animaton/images/arrow-right-XPj.png
    - assets/application/images/picker.png
    - assets/application/images/component-key.png
    - assets/application/images/folder-3RF.png
    - assets/application/images/background.png
    - assets/application/images/material-symbols-dark-mode-outline.png
    - assets/jitter-animaton/images/location-arrow-Jah.png
    - assets/application/images/arrow-right-ERj.png
    - assets/application/images/smile-7fs.png
    - assets/application/images/battery-1hw.png
    - assets/application/images/background-gs7.png
    - assets/components/images/location-arrow-v4d.png
    - assets/application/images/background-2mj.png
    - assets/application/images/background-Cay.png
    - assets/components/images/button3.png
    - assets/application/images/bell-tZb.png
    - assets/components/images/circle.png
    - assets/components/images/auto-group-vj87.png
    - assets/application/images/vector-VeV.png
    - assets/application/images/dot-1-BnD.png
    - assets/application/images/battery-WxD.png
    - assets/application/images/background-WMs.png
    - assets/application/images/cellular-signal-rWy.png
    - assets/application/images/background-WrR.png
    - assets/application/images/wifi-XYZ.png
    - assets/application/images/background-6GD.png
    - assets/application/images/cellular-signal-Sqs.png
    - assets/application/images/battery-k5s.png
    - assets/application/images/background-1xq.png
    - assets/application/images/background-XUH.png
    - assets/application/images/background-so3.png
    - assets/application/images/background-WzR.png
    - assets/application/images/wifi-cg5.png
    - assets/application/images/background-Fp9.png
    - assets/jitter-animaton/images/icon-zKo.png
    - assets/application/images/location-arrow-BxZ.png
    - assets/application/images/component-key-zHj.png
    - assets/application/images/location-arrow-uRF.png
    - assets/application/images/background-tU5.png
    - assets/application/images/battery-oVo.png
    - assets/application/images/background-Le1.png
    - assets/application/images/wifi-PDP.png
    - assets/application/images/background-dFB.png
    - assets/application/images/icon-2-r9j.png
    - assets/application/images/logo-animation.png
    - assets/application/images/button3-pRj.png
    - assets/components/images/picker-T7K.png
    - assets/components/images/property-1circle3.png
    - assets/components/images/property-1icons.png
    - assets/components/images/cellular-signal-Ysw.png
    - assets/application/images/background-DuX.png
    - assets/components/images/battery-vPw.png
    - assets/application/images/bell-PYR.png
    - assets/application/images/location-arrow-zQu.png
    - assets/application/images/nav-smP.png
    - assets/jitter-animaton/images/wifi-1xh.png
    - assets/application/images/background-wEd.png
    - assets/components/images/property-1icons3.png
    - assets/components/images/arrow-right-6nH.png
    - assets/application/images/bell-tEq.png
    - assets/components/images/bell-1qo.png
    - assets/components/images/cellular-signal-kqK.png
    - assets/application/images/text.png
    - assets/application/images/background-Cj7.png
    - assets/application/images/database-tSq.png
    - assets/jitter-animaton/images/auto-group-6kvk.png
    - assets/application/images/nav-itM.png
    - assets/components/images/step1.png
    - assets/components/images/property-1circle2.png
    - assets/components/images/nav-kRb.png
    - assets/application/images/wifi-vms.png
    - assets/components/images/property-1icons-qmf.png
    - assets/components/images/location-arrow-SqB.png
    - assets/components/images/wifi-FYh.png
    - assets/application/images/location-arrow-Fad.png
    - assets/components/images/nav-8Sh.png
    - assets/jitter-animaton/images/vector-KzM.png
    - assets/components/images/step3.png
    - assets/components/images/arrow-right-3zD.png
    - assets/components/images/picker-PkZ.png
    - assets/components/images/step2.png
    - assets/components/images/battery-in9.png
    - assets/application/images/text-Co7.png
    - assets/components/images/picker-Gmb.png
    - assets/application/images/front-image.png
    - assets/application/images/cellular-signal-9Zo.png
    - assets/components/images/wifi-DSu.png
    - assets/components/images/nav-45T.png
    - assets/components/images/property-1icons3-gDB.png
    - assets/application/images/background-PU1.png
    - assets/jitter-animaton/images/front-image-P6d.png
    - assets/components/images/picker-mzD.png
    - assets/application/images/nav-eW9.png
    - assets/components/images/picker-FCq.png
    - assets/application/images/background-qTs.png
    - assets/components/images/property-1circle1.png
    - assets/components/images/picker-opq.png
    - assets/application/images/cellular-signal-Had.png
    - assets/application/images/cellular-signal-cdK.png
    - assets/components/images/picker-X4q.png
    - assets/components/images/circle-brD.png
    - assets/components/images/circle-Q7w.png
    - assets/application/images/nav-bUy.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


